name: DEPLOY_CPANEL
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: /
        remote_path: /home2/hecja354/demos/
        remote_host: br00.hostgator.com.br
        remote_user: hecja354
        remote_port: 2222
        remote_key: ${{ secrets.RSA_PRIVATE_KEY }}
